"""new fields in user model

Revision ID: 3034c9ad5ab3
Revises: ae890d829e25
Create Date: 2025-09-01 21:21:56.958298

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3034c9ad5ab3"
down_revision = "ae890d829e25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("about_me", sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_seen")
        batch_op.drop_column("about_me")

    # ### end Alembic commands ###
